### ISSUE TITLE
Need more infos 

### ISSUE THREAD

**Issue by websnooze** [Furious-Community/furious-plugins#1]
Hi men :)
I need more information about installing plugins, configuring db's, etc. Also for the socket part, which plugins are required as chat-processor, which version? or others?

**Comment by KeithGDR** [comment]
In the works.

**Comment by websnooze** [comment]
@drixevel-dev 
thanks for wiki and descriptions but what about socket ?

**Comment by KeithGDR** [comment]
> @drixevel-dev thanks for wiki and descriptions but what about socket ?

What do you mean by socket? The socket extension?

**Comment by websnooze** [comment]
nope, the statistics plugin, I see it uses socket for changing seasons but shouldn't we install/configure a socket.io server or something like that? 

moreover on the furious-clan.com webapp, on the homepage there was something very interesting : the live list of connected players but especially the possibility to get their steamid (and redirect this link to a page) was it via socket or a plugin ? or nothing of that ?

**Comment by KeithGDR** [comment]
That code was indeed for the web app but the web app is currently unavailable. The season changing was originally built into the plugin itself anyways.
